# Generated by Django 5.2.11 on 2026-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bake',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
