# Generated by Django 5.2.11 on 2026-02-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bake_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bake',
            name='bakery',
        ),
        migrations.RemoveField(
            model_name='bake',
            name='rating',
        ),
    ]
