# Generated by Django 5.2.11 on 2026-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_bake_bakery_remove_bake_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bake',
            name='bakery',
            field=models.CharField(default='', max_length=20),
        ),
    ]
