# Generated by Django 5.2.11 on 2026-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bake_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
