# Generated by Django 5.2.11 on 2026-02-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_bake_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1)),
                ('date', models.DateField()),
                ('bake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bake')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
